# Packages
AddPackage fish
AddPackage git
AddPackage neovim

## base-devel
AddPackage autoconf
AddPackage automake
AddPackage binutils
AddPackage bison
AddPackage fakeroot
AddPackage file
AddPackage findutils
AddPackage flex
AddPackage gawk
AddPackage gcc
AddPackage gettext
AddPackage grep
AddPackage groff
AddPackage gzip
AddPackage libtool
AddPackage m4
AddPackage make
AddPackage pacman
AddPackage patch
AddPackage pkgconf
AddPackage sed
AddPackage sudo
AddPackage texinfo
AddPackage which
