#!/bin/sh
ln -sf "$HOME/.config/yadm/config" "$HOME/.local/share/yadm/repo.git/config"
ln -sf "$HOME/.config/yadm/exclude" "$HOME/.local/share/yadm/repo.git/info/exclude"
ln -sf "$HOME/.config/yadm/attributes" "$HOME/.local/share/yadm/repo.git/info/attributes"
yadm alt
