home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
xdg_config_home: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME', default=home ~ '/.config') }}"

git_projects: "{{ home }}/g"
dotfiles_repo: "{{ git_projects }}/dotfiles.git"
dotfiles_config_dir: "{{ xdg_config_home }}/dotfiles"
