home: "{{ lookup('env', 'HOME') }}"
xdg_config_home: "{{ home }}/{{ lookup('env', 'XDG_CONFIG_HOME', '.config') }}"

git_projects: "{{ home }}/g"
dotfiles_repo: "{{ git_projects }}/dotfiles.git"
dotfiles_config_dir: "{{ xdg_config_home }}/dotfiles"
