- name: "Configure"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - autogen_variables.yml

  tasks:
  - name: "Update aconfmgr"
    ansible.builtin.git:
      repo: 'https://aur.archlinux.org/aconfmgr-git.git'
      dest: '{{ git_projects }}/aconfmgr'
      force: true

  - name: "Build & install aconfmgr"
    ansible.builtin.command:
      argv:
        - /usr/bin/makepkg
        - --noconfirm
        - -si
    args:
      chdir: '{{ git_projects }}/aconfmgr'
