- name: "Configure"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - autogen_variables.yml

  tasks:
  - name: "Create dotfiles config symlink"
    ansible.builtin.file:
      src: '{{ dotfiles_config_dir }}/config'
      dest: '{{ dotfiles_repo }}/config'
      state: link
      force: true

  - name: "Create dotfiles attributes symlink"
    ansible.builtin.file:
      src: '{{ dotfiles_config_dir }}/attributes'
      dest: '{{ dotfiles_repo }}/attributes'
      state: link

  - name: "Create dotfiles exclude symlink"
    ansible.builtin.file:
      src: '{{ dotfiles_config_dir }}/exclude'
      dest: '{{ dotfiles_repo }}/exclude'
      state: link

  - name: "Update aconfmgr"
    ansible.builtin.git:
      repo: 'https://aur.archlinux.org/aconfmgr-git.git'
      dest: '{{ git_projects }}/aconfmgr'
      force: true

  - name: "Build & install aconfmgr"
    ansible.builtin.command:
      argv:
        - /usr/bin/makepkg
        - --noconfirm
        - -si
    args:
      chdir: '{{ git_projects }}/aconfmgr'
