- name: "Configure fish"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - autogen_variables.yml

  tasks:
  - name: "Configure Tide"
    ansible.builtin.command: echo 2 1 2 2 1 1 2 1 1 2 y | fish -c 'tide configure' > /dev/null
