#!/usr/bin/env fish
if not contains $PRIVATE_FISH/functions $fish_function_path
    set --prepend fish_function_path $PRIVATE_FISH/functions
end


set -g tide_character_color 5FD700
set -g tide_character_color_failure FF0000
set -g tide_character_icon \u276f
set -g tide_character_vi_icon_default \u276e
set -g tide_character_vi_icon_replace \u25b6
set -g tide_character_vi_icon_visual V
set -g tide_chruby_bg_color 303030
set -g tide_chruby_color B31209
set -g tide_chruby_icon \ue23e
set -g tide_cmd_duration_bg_color 303030
set -g tide_cmd_duration_color 87875F
set -g tide_cmd_duration_decimals 0
set -g tide_cmd_duration_icon \uf252
set -g tide_cmd_duration_threshold 3000
set -g tide_context_always_display false
set -g tide_context_bg_color 303030
set -g tide_context_color_default D7AF87
set -g tide_context_color_root D7AF00
set -g tide_context_color_ssh D7AF87
set -g tide_git_bg_color 303030
set -g tide_git_bg_color_unstable 303030
set -g tide_git_bg_color_urgent 303030
set -g tide_git_color_branch 5FD700
set -g tide_git_color_conflicted FF0000
set -g tide_git_color_dirty D7AF00
set -g tide_git_color_operation FF0000
set -g tide_git_color_staged D7AF00
set -g tide_git_color_stash 5FD700
set -g tide_git_color_untracked 00AFFF
set -g tide_git_color_upstream 5FD700
set -g tide_git_icon \uf1d3
set -g tide_go_bg_color 303030
set -g tide_go_color 00ACD7
set -g tide_go_icon \ue627
set -g tide_jobs_bg_color 303030
set -g tide_jobs_color 5FAF00
set -g tide_jobs_icon \uf013
set -g tide_kubectl_bg_color 303030
set -g tide_kubectl_color 326CE5
set -g tide_kubectl_icon \u2388
set -g tide_left_prompt_frame_enabled false
set -g tide_left_prompt_items os pwd git
set -g tide_left_prompt_prefix \u2591\u2592\u2593
set -g tide_left_prompt_separator_diff_color \ue0b0
set -g tide_left_prompt_separator_same_color \ue0b1
set -g tide_left_prompt_suffix \ue0b0
set -g tide_node_bg_color 303030
set -g tide_node_color 44883E
set -g tide_node_icon \u2b22
set -g tide_os_bg_color 303030
set -g tide_os_color EEEEEE
set -g tide_os_icon \uf303
set -g tide_php_bg_color 303030
set -g tide_php_color 617CBE
set -g tide_php_icon \ue608
set -g tide_prompt_add_newline_before false
set -g tide_prompt_color_frame_and_connection 6C6C6C
set -g tide_prompt_color_separator_same_color 949494
set -g tide_prompt_icon_connection \x20
set -g tide_prompt_min_cols 26
set -g tide_prompt_pad_items true
set -g tide_pwd_bg_color 303030
set -g tide_pwd_color_anchors 00AFFF
set -g tide_pwd_color_dirs 0087AF
set -g tide_pwd_color_truncated_dirs 8787AF
set -g tide_pwd_icon \uf07c
set -g tide_pwd_icon_home \uf015
set -g tide_pwd_icon_unwritable \uf023
set -g tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform Cargo.toml composer.json CVS go.mod package.json
set -g tide_right_prompt_frame_enabled false
set -g tide_right_prompt_items status cmd_duration context jobs virtual_env go vi_mode time
set -g tide_right_prompt_prefix \ue0b2
set -g tide_right_prompt_separator_diff_color \ue0b2
set -g tide_right_prompt_separator_same_color \ue0b3
set -g tide_right_prompt_suffix \u2593\u2592\u2591
set -g tide_rustc_bg_color 303030
set -g tide_rustc_color F74C00
set -g tide_rustc_icon \ue7a8
set -g tide_shlvl_bg_color 303030
set -g tide_shlvl_color d78700
set -g tide_shlvl_icon \uf120
set -g tide_shlvl_threshold 1
set -g tide_status_bg_color 303030
set -g tide_status_bg_color_failure 303030
set -g tide_status_color 5FAF00
set -g tide_status_color_failure D70000
set -g tide_status_icon \u2714
set -g tide_status_icon_failure \u2718
set -g tide_terraform_bg_color 303030
set -g tide_terraform_color 844FBA
set -g tide_terraform_icon \x1d
set -g tide_time_bg_color 303030
set -g tide_time_color 5F8787
set -g tide_time_format \x25T
set -g tide_vi_mode_bg_color_default 303030
set -g tide_vi_mode_bg_color_replace 303030
set -g tide_vi_mode_bg_color_visual 303030
set -g tide_vi_mode_color_default 87af00
set -g tide_vi_mode_color_replace d78700
set -g tide_vi_mode_color_visual 5f87d7
set -g tide_vi_mode_icon_default DEFAULT
set -g tide_vi_mode_icon_replace REPLACE
set -g tide_vi_mode_icon_visual VISUAL
set -g tide_virtual_env_bg_color 303030
set -g tide_virtual_env_color 00AFAF
set -g tide_virtual_env_icon \ue73c
