#!/bin/sh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_DIRS="$HOME/.nix-profile/share:/usr/share"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# General dotfiles
# shellcheck source=/dev/null
export GIT="$HOME/g"
export DOTFILES_REPO="$GIT/dotfiles/repo.git"
export SCRIPTS="$HOME/.local/bin"
export TYPER_SCRIPTS_REPOS="$GIT/typer-scripts"
