help_message = 'Domestobot maintenance routines'
default_subcommands = [
    'upgrade_fisher',
    'upgrade_os',
    'check_qtile_config',
    'upgrade_python_tools',
    'upgrade_doom',
    'save_aconfmgr',
]

[[steps]]
name = 'upgrade_fisher'
doc = "Upgrade Fish package manager (Linux only)."
[[steps.envs]]
os = 'Linux'
title = 'Upgrading fisher'
command = ['fish', '-c', 'fisher update']

[[steps]]
name = 'upgrade_os'
doc = "Upgrade using native package manager (Homebrew/Arch's Paru only)."
[[steps.envs]]
os = 'Darwin'
title = 'Upgrading with brew'
commands = [
    ['brew', 'update'],
    ['brew', 'upgrade']
]
[[steps.envs]]
os = 'Linux'
title = 'Upgrading with paru'
command = ['paru']

[[steps]]
name = 'check_qtile_config'
doc = "Checks if qtile config is valid."
[[steps.envs]]
os = 'Linux'
title = 'Checking qtile config'
command = ['qtile', 'check']

[[steps]]
name = 'upgrade_python_tools'
doc = "Upgrade Pipx tool and packages."
title = 'Upgrading pipx and packages'
command = ['pipx', 'upgrade-all']

[[steps]]
name = 'upgrade_doom'
doc = 'Upgrade doom emacs distribution.'
title = 'Upgrading doom'
command = ['doom', 'upgrade']

[[steps]]
name = 'save_aconfmgr'
doc = 'Run `aconfmgr save`.'
[[steps.envs]]
os = 'Linux'
title = 'Saving aconfmgr'
command = ['aconfmgr', 'save']
