# shellcheck source=/dev/null
. "$HOME/.config/profile"

setxkbmap -layout us -variant altgr-intl

. $HOME/.fehbg

# Make DISPLAY and XAUTHORITY available to systemd
sh /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Network Manager Widget
nm-applet &

# Udiskie
udiskie &
