setxkbmap -layout us -variant altgr-intl

. $HOME/.fehbg

# Make DISPLAY and XAUTHORITY available to systemd
sh /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Compositor (for transparency)
picom &

# Password manager
keepassxc &

# Udiskie
udiskie &
