[tool.poetry]
name = "poetry-instance"
version = "1.3.2"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.11.1"
poetry = "1.3.2"

[tool.poetry.group.additional.dependencies]
poetry-plugin-up = "^0.2.1"

