#!/bin/sh
. "$HOME/.local/share/dotfiles/platform_label"

# shellcheck disable=SC2155
export PLATFORM_TYPE="$(uname)"
export GIT="$HOME/g"
export SCRIPTS="$GIT/scripts"
export BACKUP_PATHS="\
$HOME/g $HOME/org $HOME/documents $HOME/pictures $HOME/.config/JetBrains \
$HOME/.config/rclone .mozilla"
export BACKUPDIR=/run/media/ali/backup/backup

export DIRENV_LOG_FORMAT=""

export TYPER_SCRIPTS_REPOS="$SCRIPTS $GIT/typer-scripts"

# Misc.
export VISUAL="emacs-term"
export VIRTUAL_ENV_DISABLE_PROMPT=1


common=$HOME/.config/common_profile

if [ "$PLATFORM_TYPE" = "Linux" ]; then
    # shellcheck source=/dev/null
    . "$common/linux"
elif [ "$PLATFORM_TYPE" = "Darwin" ]; then
    # shellcheck source=/dev/null
    . "$common/macos"
fi

# shellcheck source=/dev/null
[ -f "$common/work" ] && . "$common/work" # Out of source control


userpaths="\
$HOME/.local/bin $SCRIPTS/miscellaneous $SCRIPTS/backup $HOME/.poetry/bin \
$HOME/.config/emacs/bin ${PLATFORM_PATH:-}"

addpath() {
    case ":${PATH:=$1}:" in
        *:"$1":*) ;;
        *) PATH="$1:$PATH" ;;
    esac
}

for path in $userpaths; do
    addpath "$path"
done
