#!/bin/sh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home
export HOMEBREW_NO_AUTO_UPDATE=1
export __CF_USER_TEXT_ENCODING='0x0:0x0' # Don't store useless file

export PLATFORM_PATH="\
/usr/local/opt/coreutils/libexec/gnubin $HOME/Library/Haskell/bin"
