#!/bin/sh

for file in "$HOME"/.config/profile.d/*; do
    # shellcheck source=/dev/null
    . "$file"
done


# Make stubborn apps conform to XDG
export ANSIBLE_HOME="$XDG_CONFIG_HOME/ansible"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="$XDG_CACHE_HOME/ansible/galaxy_cache"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export AWS_SHARED_CREDENTIALS_FILE="$XDG_DATA_HOME"/aws/credentials
export AZURE_CONFIG_DIR="$XDG_DATA_HOME"/azure
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CHROME_CONFIG_HOME="$XDG_DATA_HOME"
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export HISTFILE="$XDG_STATE_HOME/bash/history"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export LESSHISTFILE="$XDG_DATA_HOME/state/history"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PIPX_HOME="$XDG_DATA_HOME/pipx"
export PIPX_BIN_DIR="$PIPX_HOME/bin"
export PIPX_DEFAULT_PYTHON="$(pyenv which python)"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"


# Backups
export BACKUP_PATHS="\
$GIT $HOME/org $HOME/documents $HOME/pictures $HOME/.config/JetBrains \
$HOME/.config/rclone $HOME/.mozilla $PIPX_HOME/venvs $HOME/.config/Ferdium"
export BACKUPDIR=/run/media/ali/backup/backup


# Misc.
if [ "$PLATFORM_LABEL" = 'main' ]; then
    export BROWSER='firefox'
else
    export BROWSER='brave'
fi

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
export KAFKA="$HOME/documents/courses/kafka/kafka_2.13-3.3.1"
export LIBVA_DRIVER_NAME="iHD" # Hardware video acceleration
export MOZ_DISABLE_RDD_SANDBOX=1 # https://bugzilla.mozilla.org/show_bug.cgi?id=1751363
export QT_QPA_PLATFORMTHEME=qt5ct
export SUDO_ASKPASS="$SCRIPTS/miscellaneous/rbw-askpass"
export TERM="xterm-256color"
export VISUAL="emacs-term"
export VIRTUAL_ENV_DISABLE_PROMPT=1  # Disable message when activating a python venv


# PATH
export PATH="$SCRIPTS/miscellaneous:$HOME/.nix-profile/bin:$HOME/.local/bin:\
$PIPX_BIN_DIR:$SCRIPTS/backup:$HOME/.poetry/bin:$HOME/.emacs.d/bin:/opt/mssql/bin:\
${PLATFORM_PATH:-}:$SCRIPTS/config:$PATH:$HOME/documents/courses/kafka/kafka_2.13-3.3.1/bin"
