#!/bin/sh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Make stubborn apps conform to XDG
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CHROME_CONFIG_HOME="$XDG_DATA_HOME"
export HISTFILE="$XDG_STATE_HOME/bash/history"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export LESSHISTFILE="$XDG_DATA_HOME/state/history"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PIPX_HOME="$XDG_DATA_HOME/pipx"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"


# General dotfiles
# shellcheck source=/dev/null
. "$HOME/.local/share/dotfiles/platform_label"
export DOTFILES_REPO="$XDG_DATA_HOME/dotfiles/repo.git"
export GIT="$HOME/g"
export SCRIPTS="$GIT/scripts"
export TYPER_SCRIPTS_REPOS="$SCRIPTS $GIT/typer-scripts"


# Backups
export BACKUP_PATHS="\
$GIT $HOME/org $HOME/documents $HOME/pictures $HOME/.config/JetBrains \
$HOME/.config/rclone .mozilla $PIPX_HOME/venvs"
export BACKUPDIR=/run/media/ali/backup/backup


# Misc.
export BROWSER="firefox"
export DIRENV_LOG_FORMAT=""
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
export LIBVA_DRIVER_NAME="iHD" # Hardware video acceleration
export QT_QPA_PLATFORMTHEME=qt5ct
export RCLONE_PASSWORD_COMMAND="secret-tool lookup program rclone user ali"
export TERM="xterm-256color"
export VISUAL="emacs-term"
export VIRTUAL_ENV_DISABLE_PROMPT=1  # Disable message when activating an env


# PATH
userpaths="\
$HOME/.local/bin $SCRIPTS/miscellaneous $SCRIPTS/backup $HOME/.poetry/bin \
$HOME/.config/emacs/bin /opt/mssql/bin ${PLATFORM_PATH:-}"

addpath() {
    case ":${PATH:=$1}:" in
        *:"$1":*) ;;
        *) PATH="$1:$PATH" ;;
    esac
}

for path in $userpaths; do
    addpath "$path"
done
